# Generated by Django 6.0.5 on 2026-09-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=False)),
                ('nome_app', models.CharField(blank=True, max_length=150)),
                ('nome_exibicao', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mobile/logos/')),
                ('banner_principal', models.ImageField(blank=True, null=True, upload_to='mobile/banners/')),
                ('mensagem_boas_vindas', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('horarios_cultos', models.TextField(blank=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Configuração do aplicativo',
                'verbose_name_plural': 'Configuração do aplicativo',
                'constraints': [models.UniqueConstraint(fields=('igreja',), name='unique_mobile_config_igreja')],
            },
        ),
        migrations.CreateModel(
            name='PalavraDoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('referencia_biblica', models.CharField(blank=True, max_length=255)),
                ('texto_biblico', models.TextField(blank=True)),
                ('reflexao', models.TextField(blank=True)),
                ('aplicacao', models.TextField(blank=True)),
                ('oracao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mobile/palavras-do-dia/')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=30)),
                ('publicado', models.BooleanField(default=False)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Palavra do dia',
                'verbose_name_plural': 'Palavras do dia',
                'ordering': ('-data', '-id'),
                'constraints': [models.UniqueConstraint(fields=('igreja', 'data'), name='unique_palavra_dia_igreja_data')],
            },
        ),
    ]
