# Generated by Django 6.0.5 on 2026-09-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('pedido', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Pedido de oração',
                'verbose_name_plural': 'Pedidos de oração',
                'ordering': ('-criado_em',),
            },
        ),
    ]
