# Generated by Django 6.0.5 on 2026-09-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mensagemapp_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemapp',
            options={'ordering': ('data', 'ordem', '-created_at'), 'verbose_name': 'Mensagem do aplicativo', 'verbose_name_plural': 'Mensagens do aplicativo'},
        ),
    ]
