# Generated by Django 6.0.5 on 2026-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_alter_mensagemapp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemapp',
            options={'ordering': ('data', 'ordem', '-created_at'), 'verbose_name': 'Mensagem do dia do app', 'verbose_name_plural': 'Mensagens do dia do app'},
        ),
    ]
