# Generated by Django 6.0.5 on 2026-10-06 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
        ('mobile', '0007_alter_mensagemapp_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitante_id', models.CharField(db_index=True, max_length=100)),
                ('canal', models.CharField(choices=[('app', 'Aplicativo'), ('portal', 'Portal')], default='app', max_length=20)),
                ('evento', models.CharField(db_index=True, max_length=80)),
                ('recurso', models.CharField(blank=True, max_length=120)),
                ('dispositivo', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('acessado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso do aplicativo',
                'verbose_name_plural': 'Acessos do aplicativo',
                'ordering': ('-acessado_em',),
                'indexes': [models.Index(fields=['igreja', 'evento', 'acessado_em'], name='mobile_aces_igreja__ead3cc_idx'), models.Index(fields=['igreja', 'recurso', 'acessado_em'], name='mobile_aces_igreja__7f436c_idx')],
            },
        ),
    ]
