# Generated by Django 6.0.5 on 2026-05-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='plano',
            field=models.CharField(choices=[('GRATUITO', 'Gratuito'), ('COMPLETO', 'Completo')], default='GRATUITO', max_length=20),
        ),
    ]
