# Generated by Django 6.0.5 on 2026-08-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150)),
                ('categoria', models.CharField(choices=[('CULTO', 'Culto'), ('REUNIAO', 'Reunião'), ('EBD', 'EBD'), ('CONFERENCIA', 'Conferência'), ('RETIRO', 'Retiro'), ('JUVENTUDE', 'Juventude'), ('HOMENS', 'Homens'), ('MULHERES', 'Mulheres'), ('MINISTERIO', 'Ministério'), ('ESPECIAL', 'Evento Especial'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ('data', 'hora_inicio', 'titulo'),
            },
        ),
    ]
