# Generated by Django 6.0.5 on 2026-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='destaque_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='exibir_site',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/mobile/'),
        ),
    ]
