# Generated by Django 6.0.5 on 2026-05-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoMissionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.FileField(upload_to='acoes_missionarias/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('data_acao', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acao missionaria',
                'verbose_name_plural': 'Acoes missionarias',
                'ordering': ('-destaque', '-data_acao', '-created_at'),
            },
        ),
    ]
