# Generated by Django 6.0.5 on 2026-08-25 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('igrejas', '0002_igreja_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemAniversario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(default='Olá, {nome}! 🎉\n\nDesejamos a você um feliz aniversário! Que Deus abençoe sua vida e sua caminhada. 🙏')),
                ('versiculo', models.TextField(blank=True, default='“O Senhor te abençoe e te guarde.” — Números 6:24')),
                ('ativa', models.BooleanField(default=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'verbose_name': 'Mensagem de aniversário',
                'verbose_name_plural': 'Mensagens de aniversário',
                'constraints': [models.UniqueConstraint(fields=('igreja',), name='unique_mensagem_aniversario_igreja')],
            },
        ),
    ]
