# Generated by Django 6.0.5 on 2026-09-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_fechamentofinanceiromensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
    ]
