# Generated by Django 6.0.5 on 2026-09-03 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portal/avisos/')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('exibir_site', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'ordering': ('-destaque', 'ordem', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BannerSiteIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portal/banners/')),
                ('imagem_mobile', models.ImageField(blank=True, null=True, upload_to='portal/banners/mobile/')),
                ('texto_botao', models.CharField(blank=True, max_length=80)),
                ('link_botao', models.URLField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portal/programacao/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('exibir_site', models.BooleanField(default=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'ordering': ('dia_semana', 'ordem', 'horario_inicio'),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSiteIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo_site', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('slug_publico', models.SlugField(blank=True, null=True)),
                ('dominio_personalizado', models.CharField(blank=True, max_length=255)),
                ('site_ativo', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portal/logos/')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='portal/capas/')),
                ('imagem_padrao', models.ImageField(blank=True, null=True, upload_to='portal/padroes/')),
                ('cor_primaria', models.CharField(default='#14532d', max_length=7)),
                ('cor_secundaria', models.CharField(default='#0f172a', max_length=7)),
                ('cor_destaque', models.CharField(default='#d9a441', max_length=7)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email_publico', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('texto_sobre', models.TextField(blank=True)),
                ('foto_pastor', models.ImageField(blank=True, null=True, upload_to='portal/pastor/')),
                ('nome_pastor', models.CharField(blank=True, max_length=150)),
                ('descricao_pastor', models.TextField(blank=True)),
                ('exibir_eventos', models.BooleanField(default=True)),
                ('exibir_programacao', models.BooleanField(default=True)),
                ('exibir_avisos', models.BooleanField(default=True)),
                ('exibir_pastor', models.BooleanField(default=True)),
                ('exibir_redes_sociais', models.BooleanField(default=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('igreja',), name='unique_portal_site_igreja')],
            },
        ),
    ]
