# Generated by Django 6.0.5 on 2026-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='descricao_contribuicao',
            field=models.CharField(blank=True, default='Sua generosidade faz a diferença.', max_length=180),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='descricao_oracao',
            field=models.CharField(blank=True, default='Conte seus pedidos, estamos orando por você.', max_length=180),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='descricao_transmissao',
            field=models.CharField(blank=True, default='Acompanhe nossos cultos ao vivo.', max_length=180),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='descricao_visitar',
            field=models.CharField(blank=True, default='Será uma alegria receber você!', max_length=180),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='horarios_texto',
            field=models.TextField(blank=True, default='Domingo\n09h00 - Escola Bíblica Dominical\n10h15 - Culto da Manhã\n18h30 - Culto da Noite\n\nQuarta-feira\n19h30 - Culto de Oração'),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='pix_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portal/pix/'),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='texto_contribuicao',
            field=models.CharField(blank=True, default='Contribua', max_length=80),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='texto_oracao',
            field=models.CharField(blank=True, default='Pedido de oração', max_length=80),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='texto_transmissao',
            field=models.CharField(blank=True, default='Transmissões', max_length=80),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='texto_visitar',
            field=models.CharField(blank=True, default='Quero visitar', max_length=80),
        ),
        migrations.AddField(
            model_name='configuracaositeigreja',
            name='transmissao_url',
            field=models.URLField(blank=True),
        ),
    ]
