from django.db import models
from apps.core.models import TenantModel
class ConfiguracaoSiteIgreja(TenantModel):
    titulo_site=models.CharField(max_length=200,blank=True); descricao=models.TextField(blank=True); slogan=models.CharField(max_length=255,blank=True); slug_publico=models.SlugField(blank=True,null=True); dominio_personalizado=models.CharField(max_length=255,blank=True); site_ativo=models.BooleanField(default=True)
    logo=models.ImageField(upload_to='portal/logos/',blank=True,null=True); imagem_capa=models.ImageField(upload_to='portal/capas/',blank=True,null=True); imagem_padrao=models.ImageField(upload_to='portal/padroes/',blank=True,null=True)
    cor_primaria=models.CharField(max_length=7,default='#14532d'); cor_secundaria=models.CharField(max_length=7,default='#0f172a'); cor_destaque=models.CharField(max_length=7,default='#d9a441')
    telefone=models.CharField(max_length=30,blank=True); whatsapp=models.CharField(max_length=30,blank=True); email_publico=models.EmailField(blank=True); endereco=models.CharField(max_length=255,blank=True); bairro=models.CharField(max_length=100,blank=True); cidade=models.CharField(max_length=100,blank=True); estado=models.CharField(max_length=2,blank=True); instagram=models.URLField(blank=True); facebook=models.URLField(blank=True); youtube=models.URLField(blank=True); transmissao_url=models.URLField(blank=True); horarios_texto=models.TextField(blank=True,default='Domingo\n09h00 - Escola Bíblica Dominical\n10h15 - Culto da Manhã\n18h30 - Culto da Noite\n\nQuarta-feira\n19h30 - Culto de Oração'); pix_imagem=models.ImageField(upload_to='portal/pix/',blank=True,null=True); texto_visitar=models.CharField(max_length=80,blank=True,default='Quero visitar'); descricao_visitar=models.CharField(max_length=180,blank=True,default='Será uma alegria receber você!'); texto_oracao=models.CharField(max_length=80,blank=True,default='Pedido de oração'); descricao_oracao=models.CharField(max_length=180,blank=True,default='Conte seus pedidos, estamos orando por você.'); texto_transmissao=models.CharField(max_length=80,blank=True,default='Transmissões'); descricao_transmissao=models.CharField(max_length=180,blank=True,default='Acompanhe nossos cultos ao vivo.'); texto_contribuicao=models.CharField(max_length=80,blank=True,default='Contribua'); descricao_contribuicao=models.CharField(max_length=180,blank=True,default='Sua generosidade faz a diferença.'); texto_sobre=models.TextField(blank=True); foto_pastor=models.ImageField(upload_to='portal/pastor/',blank=True,null=True); nome_pastor=models.CharField(max_length=150,blank=True); descricao_pastor=models.TextField(blank=True); exibir_eventos=models.BooleanField(default=True); exibir_programacao=models.BooleanField(default=True); exibir_avisos=models.BooleanField(default=True); exibir_pastor=models.BooleanField(default=True); exibir_redes_sociais=models.BooleanField(default=True)
    class Meta: constraints=[models.UniqueConstraint(fields=('igreja',),name='unique_portal_site_igreja')]
    def __str__(self): return self.titulo_site or self.igreja.nome
    @property
    def nome_publico(self): return self.titulo_site or self.igreja.nome
class BannerSiteIgreja(TenantModel):
    titulo=models.CharField(max_length=200); subtitulo=models.CharField(max_length=255,blank=True); descricao=models.TextField(blank=True); imagem=models.ImageField(upload_to='portal/banners/',blank=True,null=True); imagem_mobile=models.ImageField(upload_to='portal/banners/mobile/',blank=True,null=True); texto_botao=models.CharField(max_length=80,blank=True); link_botao=models.URLField(blank=True); data_inicio=models.DateField(blank=True,null=True); data_fim=models.DateField(blank=True,null=True); ordem=models.PositiveIntegerField(default=0); ativo=models.BooleanField(default=True)
    class Meta: ordering=('ordem','id')
class ProgramacaoIgreja(TenantModel):
    DIAS=[(0,'Domingo'),(1,'Segunda-feira'),(2,'Terça-feira'),(3,'Quarta-feira'),(4,'Quinta-feira'),(5,'Sexta-feira'),(6,'Sábado')]
    titulo=models.CharField(max_length=150); descricao=models.TextField(blank=True); dia_semana=models.PositiveSmallIntegerField(choices=DIAS); horario_inicio=models.TimeField(); horario_fim=models.TimeField(blank=True,null=True); local=models.CharField(max_length=150,blank=True); imagem=models.ImageField(upload_to='portal/programacao/',blank=True,null=True); ordem=models.PositiveIntegerField(default=0); ativo=models.BooleanField(default=True); exibir_site=models.BooleanField(default=True)
    class Meta: ordering=('dia_semana','ordem','horario_inicio')
class AvisoIgreja(TenantModel):
    titulo=models.CharField(max_length=200); descricao=models.TextField(); imagem=models.ImageField(upload_to='portal/avisos/',blank=True,null=True); data_inicio=models.DateField(blank=True,null=True); data_fim=models.DateField(blank=True,null=True); destaque=models.BooleanField(default=False); exibir_site=models.BooleanField(default=True); ativo=models.BooleanField(default=True); ordem=models.PositiveIntegerField(default=0)
    class Meta: ordering=('-destaque','ordem','-id')