# Generated by Django 6.0.5 on 2026-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='necessita_cuidado_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membro',
            name='observacao_cuidado_especial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='prioridade_cuidado',
            field=models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='responsavel_cuidado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='tipo_cuidado_especial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
