# Generated by Django 6.0.5 on 2026-08-24 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
        ('membros', '0002_membro_necessita_cuidado_especial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='data_primeira_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='observacao_visitante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='origem_visitante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='responsavel_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membro',
            name='status_visitante',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('ACOMPANHAMENTO', 'Em acompanhamento'), ('RETORNOU', 'Retornou'), ('FREQUENTE', 'Frequente'), ('INTEGRADO', 'Integrado'), ('SEM_RETORNO', 'Sem retorno')], default='NOVO', max_length=30),
        ),
        migrations.AddField(
            model_name='membro',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VisitaVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_visita', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_visitante', to='membros.membro')),
            ],
            options={
                'ordering': ('data_visita', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('24H', 'Contato de 24 horas'), ('7D', 'Contato de 7 dias'), ('15D', 'Contato de 15 dias'), ('RETORNO', 'Nova tentativa')], max_length=20)),
                ('data_prevista', models.DateField()),
                ('data_realizada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos_visitante_responsaveis', to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos_visitante', to='membros.membro')),
            ],
            options={
                'ordering': ('data_prevista', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo__in', ('24H', '7D', '15D'))), fields=('visitante', 'tipo'), name='unique_jornada_visitante_tipo')],
            },
        ),
    ]
