# Generated by Django 6.0.5 on 2026-08-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0002_igreja_plano'),
        ('membros', '0003_membro_data_primeira_visita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemWhatsAppVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('24H', 'Mensagem de 24 horas'), ('7D', 'Mensagem de 7 dias'), ('15D', 'Mensagem de 15 dias')], max_length=20)),
                ('mensagem', models.TextField()),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('igreja', 'tipo'), name='unique_mensagem_whatsapp_igreja_tipo')],
            },
        ),
    ]
