# Generated by Django 6.0.5 on 2026-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_mensagemwhatsappvisitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='autoriza_exibir_aniversario_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros/'),
        ),
    ]
